// Class: Readall
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::all
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.12/04       [396292]
Creator        : ntonon
Date           : Wed Feb 14 17:57:57 2018
Host           : Linux sbgat230 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/ntonon/Bureau/these/tHq/code/Analysis
Training events: 26999
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
nCuts: "100" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "4.000000e-01" [Learning rate for GradBoost algorithm]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "pray" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 10
nJet25                        nJet25                        nJet25                        nJet25                                                          'F'    [0,13]
maxEtaJet25                   maxEtaJet25                   maxEtaJet25                   maxEtaJet25                                                     'F'    [0.000388414860936,5.07888269424]
lepCharge                     lepCharge                     lepCharge                     lepCharge                                                       'F'    [-1,1]
nJetEta1                      nJetEta1                      nJetEta1                      nJetEta1                                                        'F'    [0,8]
dEtaFwdJetBJet                dEtaFwdJetBJet                dEtaFwdJetBJet                dEtaFwdJetBJet                                                  'F'    [0.000170946121216,7.24128103256]
dEtaFwdJet2BJet               dEtaFwdJet2BJet               dEtaFwdJet2BJet               dEtaFwdJet2BJet                                                 'F'    [-1,6.96568489075]
dEtaFwdJetClosestLep          dEtaFwdJetClosestLep          dEtaFwdJetClosestLep          dEtaFwdJetClosestLep                                            'F'    [1.13248825073e-06,5.82162666321]
dPhiHighestPtSSPair           dPhiHighestPtSSPair           dPhiHighestPtSSPair           dPhiHighestPtSSPair                                             'F'    [0.051636043936,9.42442703247]
minDRll                       minDRll                       minDRll                       minDRll                                                         'F'    [0.0303395278752,3.35241937637]
Lep3Pt                        Lep3Pt                        Lep3Pt                        Lep3Pt                                                          'F'    [15.0019569397,460.266387939]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new allNode
   
#ifndef allNode__def
#define allNode__def
   
class allNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   allNode ( allNode* left,allNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~allNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   allNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   allNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   allNode*   fLeft;     // pointer to the left daughter node
   allNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   allNode::~allNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool allNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool allNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Readall : public IClassifierReader {

 public:

   // constructor
   Readall( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Readall" ),
        fNvars( 10 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "nJet25", "maxEtaJet25", "lepCharge", "nJetEta1", "dEtaFwdJetBJet", "dEtaFwdJet2BJet", "dEtaFwdJetClosestLep", "dPhiHighestPtSSPair", "minDRll", "Lep3Pt" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~Readall() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[10];
   double fVmax[10];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[10];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<allNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double Readall::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      allNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(allNode*)current->GetRight();
         else current=(allNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void Readall::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733685,0.186948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.46813,-0.025496) , 
8, 1.04584, 1, 0, 0.61659,0.11659) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.407439,-0.0740488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233053,-0.213558) , 
0, 4.08911, 1, 0, 0.3242,-0.1758) , 
0, 3.08911, 1, 0, 0.5,9.20684e-14)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.536643,-0.000755494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.80209,0.202111) , 
6, 1.26494, 1, 0, 0.706223,0.15747) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.298858,-0.146916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.479043,-9.1441e-05) , 
6, 0.864616, 1, 0, 0.411776,-0.0673057) , 
0, 2.05941, 1, 0, 0.5,4.27655e-05)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721045,0.12684) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.339934,-0.0328272) , 
0, 4.08911, 1, 0, 0.641778,0.110661) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543008,0.00418256) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.265412,-0.115093) , 
0, 3.08911, 1, 0, 0.43433,-0.0506339) , 
8, 0.622393, 1, 0, 0.5,0.00042603)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503761,-0.00584341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.316423,-0.0881675) , 
5, -0.931543, 1, 0, 0.40678,-0.0562403) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673859,0.0953257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413868,-0.0563933) , 
8, 1.47372, 1, 0, 0.632423,0.0803571) , 
6, 1.7292, 1, 0, 0.5,0.000192267)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431832,-0.0322359) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.135637,-0.151076) , 
0, 4.06931, 1, 0, 0.375081,-0.0602228) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.628058,0.0576641) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.346975,-0.0752502) , 
8, 1.64971, 1, 0, 0.585344,0.0413425) , 
1, 1.96139, 1, 0, 0.5,0.00011807)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.728885,0.117879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483445,0.0105632) , 
8, 0.569152, 1, 0, 0.558237,0.0468208) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.392344,-0.0846037) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523256,0.0250328) , 
7, 7.41786, 1, 0, 0.451573,-0.0392869) , 
7, 4.22763, 1, 0, 0.5,-0.000192591)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.733864,0.0937459) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.665411,0.000954036) , 
9, 35.3736, 1, 0, 0.706223,0.0614836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.432261,-0.0138351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.175935,-0.139792) , 
8, 2.00385, 1, 0, 0.411776,-0.0262926) , 
0, 2.05941, 1, 0, 0.5,7.42999e-06)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402794,-0.0383332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.626542,0.0379589) , 
1, 1.45409, 1, 0, 0.562752,0.0168596) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.35569,-0.0103631) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18059,-0.100855) , 
8, 0.543698, 1, 0, 0.233053,-0.0716964) , 
0, 4.11881, 1, 0, 0.5,4.59835e-06)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553091,-0.0119797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642752,0.056767) , 
2, -0.980198, 1, 0, 0.606389,0.0299975) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.477872,0.0239804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305848,-0.0830265) , 
9, 32.4624, 1, 0, 0.394776,-0.0300324) , 
8, 0.91842, 1, 0, 0.5,-0.000182718)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546131,0.0139999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233476,-0.103278) , 
8, 2.10253, 1, 0, 0.5279,0.00780935) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193488,-0.092493) , 
0, 5.0198, 1, 0, 0.5,-0.000195286)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414882,-0.0647762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.58021,0.04206) , 
7, 1.7881, 1, 0, 0.558237,0.0283529) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402415,-0.0516097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.54918,0.0344136) , 
7, 8.03526, 1, 0, 0.451573,-0.0241103) , 
7, 4.22763, 1, 0, 0.5,-0.000291176)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.44782,-0.0194167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.616035,0.0753448) , 
5, 3.68958, 1, 0, 0.459532,-0.0133798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.691868,0.078745) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.600652,0.0139852) , 
9, 31.976, 1, 0, 0.645545,0.0472466) , 
4, 3.3698, 1, 0, 0.5,-0.000190252)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.736622,0.0580322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.511052,0.00325137) , 
8, 0.711261, 1, 0, 0.597144,0.023255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.355117,-0.0387779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620391,0.0460049) , 
5, 3.65547, 1, 0, 0.407451,-0.0222656) , 
5, -0.921132, 1, 0, 0.5,-5.66798e-05)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581312,0.0058488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588632,0.0995153) , 
8, 0.980611, 1, 0, 0.585377,0.0626836) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.619951,0.0171412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.381022,-0.027593) , 
8, 0.819745, 1, 0, 0.489006,-0.00806498) , 
9, 19.4105, 1, 0, 0.5,6.13774e-06)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.582338,0.0264986) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.266387,-0.0523693) , 
8, 1.81344, 1, 0, 0.54306,0.0169436) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.378122,-0.0558524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.523112,0.0171818) , 
7, 7.39862, 1, 0, 0.45345,-0.0183405) , 
7, 4.87723, 1, 0, 0.5,-1.13713e-05)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440879,-0.0116983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625229,0.0238477) , 
4, 2.22269, 1, 0, 0.5279,0.00465087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193488,-0.0606149) , 
0, 5.0198, 1, 0, 0.5,-4.83304e-05)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583639,-0.0254258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725376,0.0947917) , 
9, 45.9367, 1, 0, 0.661121,0.0374073) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514628,0.0102547) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.401189,-0.0379741) , 
9, 41.1926, 1, 0, 0.477431,-0.00531038) , 
8, 0.359258, 1, 0, 0.5,-6.19503e-05)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467956,-0.00194479) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.688706,0.0405788) , 
4, 3.4119, 1, 0, 0.509116,0.00554602) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.33103,-0.068562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.568678,0.00427524) , 
1, 3.04525, 1, 0, 0.447176,-0.0321573) , 
3, 2.05941, 1, 0, 0.5,-3.13047e-06)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.618828,0.0305531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.515398,-0.00776854) , 
7, 4.87949, 1, 0, 0.570278,0.0119882) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229546,-0.0908998) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.444139,-0.00422988) , 
5, 0.873349, 1, 0, 0.418035,-0.0139842) , 
5, 0.419627, 1, 0, 0.5,-1.0765e-06)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.478911,-0.000867833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652779,0.0505684) , 
5, 3.81096, 1, 0, 0.492218,0.00302425) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630751,-0.0563925) , 
6, 3.40075, 1, 0, 0.5,-4.11417e-05)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.440787,-0.0415165) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.602603,0.0315011) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.467053,-0.00679096) , 
7, 3.32372, 1, 0, 0.505221,0.0036405) , 
7, 2.00043, 1, 0, 0.5,4.52148e-06)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.581312,0.00364546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.588632,0.0558766) , 
8, 0.980611, 1, 0, 0.585377,0.0342426) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.58585,0.00636533) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340245,-0.0206227) , 
8, 1.11577, 1, 0, 0.489006,-0.00439789) , 
9, 19.4105, 1, 0, 0.5,1.02936e-05)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.520124,0.00328405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.3937,-0.0300153) , 
7, 5.89846, 1, 0, 0.48905,-0.00497054) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557892,0.0683477) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.541977,-0.0136309) , 
2, -0.980198, 1, 0, 0.548899,0.0221945) , 
7, 8.03243, 1, 0, 0.5,-2.55424e-07)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.51648,0.0491086) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.613838,0.00159621) , 
4, 0.699502, 1, 0, 0.597144,0.0102855) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318261,0.0102696) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512307,-0.0324067) , 
1, 2.36386, 1, 0, 0.407451,-0.00981522) , 
5, -0.921132, 1, 0, 0.5,-8.34953e-06)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.322202,-0.0570623) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487211,-0.000788501) , 
4, 0.273443, 1, 0, 0.476815,-0.00425465) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.724425,0.0487585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586998,0.0128654) , 
5, 1.99699, 1, 0, 0.664572,0.0301486) , 
4, 3.94335, 1, 0, 0.5,-6.4536e-06)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.571576,-0.0434036) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.542702,0.0349811) , 
8, 0.722047, 1, 0, 0.550523,0.0149848) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363098,-0.0860343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.493245,0.0013251) , 
7, 2.00043, 1, 0, 0.483863,-0.00478684) , 
9, 23.8191, 1, 0, 0.5,-6.47326e-07)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.583639,-0.0109217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.725376,0.0621386) , 
9, 45.9367, 1, 0, 0.661121,0.0251479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541096,0.00360733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.186298,-0.0460926) , 
0, 4.11881, 1, 0, 0.477431,-0.00352949) , 
8, 0.359258, 1, 0, 0.5,-6.08782e-06)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382321,0.00957532) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343509,-0.0638971) , 
6, 0.424844, 1, 0, 0.367273,-0.0195204) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391692,0.0527407) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53669,0.000622958) , 
1, 1.24243, 1, 0, 0.526924,0.00392299) , 
3, 0.0792079, 1, 0, 0.5,-3.05453e-05)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474017,-0.00236615) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.645846,0.0573747) , 
5, 3.68958, 1, 0, 0.487931,0.00238762) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633874,-0.0295561) , 
6, 3.17019, 1, 0, 0.5,-4.82198e-05)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.330239,-0.040207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497763,0.000394378) , 
6, 0.104052, 1, 0, 0.487371,-0.00210154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678567,0.0318836) , 
4, 4.44521, 1, 0, 0.5,-1.00321e-05)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415045,-0.0059814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.414104,0.0591576) , 
5, 1.83747, 1, 0, 0.414853,0.00675872) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.787846,0.034144) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.486833,-0.0357802) , 
0, 2.05941, 1, 0, 0.615327,-0.00917211) , 
1, 2.56478, 1, 0, 0.5,-7.56701e-06)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489553,0.0198344) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487464,-0.0279593) , 
2, -0.980198, 1, 0, 0.488366,-0.00688211) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261056,-0.039409) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560355,0.0177831) , 
6, 0.864863, 1, 0, 0.516387,0.00968502) , 
3, 1.0297, 1, 0, 0.5,-3.6011e-06)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545803,-0.0156355) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.608944,0.0223367) , 
2, -0.980198, 1, 0, 0.582871,0.00619332) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.342258,0.0341507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.38562,-0.0378208) , 
4, 1.43405, 1, 0, 0.368315,-0.00986844) , 
8, 1.14866, 1, 0, 0.5,-1.04503e-05)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.404121,0.00505249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550842,-0.0280127) , 
1, 2.54335, 1, 0, 0.446587,-0.00418222) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.788209,0.0438396) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.439094,-0.0299692) , 
0, 3.0198, 1, 0, 0.671976,0.0133362) , 
6, 2.42088, 1, 0, 0.5,-3.06678e-05)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489553,0.0142894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487464,-0.0228265) , 
2, -0.980198, 1, 0, 0.488366,-0.00635889) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500517,0.000639099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.587327,0.0479156) , 
7, 8.03658, 1, 0, 0.516387,0.00902345) , 
3, 1.0297, 1, 0, 0.5,2.77026e-05)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617022,0.025462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272899,-0.0562068) , 
8, 1.63495, 1, 0, 0.563096,0.0118023) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.568942,0.00599343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.37111,-0.0185081) , 
5, -0.921132, 1, 0, 0.467955,-0.00596299) , 
7, 3.29963, 1, 0, 0.5,2.05891e-05)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.318261,-0.0408545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.502297,0.00443601) , 
4, 0.260193, 1, 0, 0.492218,0.00183647) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.630751,-0.0348601) , 
6, 3.40075, 1, 0, 0.5,-3.11997e-06)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.414452,0.0043612) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551859,-0.0320087) , 
1, 2.53936, 1, 0, 0.446721,-0.00378239) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.608862,-0.0213478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683798,0.0336905) , 
2, -0.980198, 1, 0, 0.654913,0.0109829) , 
1, 3.01732, 1, 0, 0.5,-3.75375e-06)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.411743,0.00246966) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408636,-0.0637621) , 
4, 1.74972, 1, 0, 0.411308,-0.00653103) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.469657,0.0534214) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620389,-0.00726096) , 
6, 1.32666, 1, 0, 0.586972,0.00644776) , 
4, 2.0793, 1, 0, 0.5,2.19087e-05)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381764,0.00593151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293943,-0.069474) , 
1, 1.15535, 1, 0, 0.360721,-0.0112705) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451549,0.0520415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.560408,0.0006245) , 
1, 1.63788, 1, 0, 0.552416,0.00423618) , 
1, 1.45857, 1, 0, 0.5,-3.87646e-06)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401174,0.0321584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.349304,-0.0373395) , 
4, 0.513032, 1, 0, 0.367273,-0.0138515) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486165,-0.0246412) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532224,0.00655225) , 
7, 2.27883, 1, 0, 0.526924,0.00276887) , 
3, 0.0792079, 1, 0, 0.5,-3.40173e-05)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.514516,-0.00593257) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.63298,0.0343858) , 
7, 2.72067, 1, 0, 0.563096,0.00944878) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.441953,-0.00955879) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.651033,0.0282313) , 
4, 3.94335, 1, 0, 0.467955,-0.00485212) , 
7, 3.29963, 1, 0, 0.5,-3.53956e-05)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518768,0.00306825) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.360816,-0.038839) , 
7, 6.00236, 1, 0, 0.492794,-0.00370642) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417966,0.0540959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567026,-0.00816684) , 
1, 1.50214, 1, 0, 0.521546,0.0110418) , 
7, 7.38283, 1, 0, 0.5,-1.0117e-05)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382773,-0.0224608) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.649962,0.0326659) , 
1, 1.93872, 1, 0, 0.550523,0.011149) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640203,0.0124999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374613,-0.0145402) , 
8, 0.721069, 1, 0, 0.483863,-0.00360554) , 
9, 23.8191, 1, 0, 0.5,-3.38484e-05)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467513,-0.00138041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.730587,0.0484367) , 
6, 2.79284, 1, 0, 0.487931,0.00192393) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633874,-0.0244604) , 
6, 3.17019, 1, 0, 0.5,-1.42476e-05)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.546131,0.00421322) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.233476,-0.0439978) , 
8, 2.10253, 1, 0, 0.5279,0.00160079) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.193488,-0.023459) , 
0, 5.0198, 1, 0, 0.5,1.06662e-05)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374957,-0.0325415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.556425,0.00217978) , 
4, 0.614078, 1, 0, 0.531438,-0.00261016) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360769,0.0654759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.26535,-0.0240265) , 
2, -0.980198, 1, 0, 0.30898,0.0157667) , 
8, 1.77361, 1, 0, 0.5,-1.31273e-05)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423969,0.0362991) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319373,-0.0287201) , 
7, 6.36003, 1, 0, 0.390426,0.015037) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545894,-0.000107413) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231238,-0.0509572) , 
8, 2.00385, 1, 0, 0.523036,-0.00322149) , 
4, 0.717113, 1, 0, 0.5,-4.97654e-05)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.744342,0.0132383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438063,-0.00872889) , 
0, 2.05941, 1, 0, 0.531438,-0.00262255) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.327428,0.0583241) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293602,-0.0163827) , 
4, 1.57744, 1, 0, 0.30898,0.0154995) , 
8, 1.77361, 1, 0, 0.5,-6.15275e-05)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491423,0.000524456) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408651,-0.0409777) , 
5, 3.0954, 1, 0, 0.486398,-0.00191829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.638579,0.0205231) , 
5, 3.81096, 1, 0, 0.5,-6.18168e-05)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.334395,-0.0320567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524098,0.00233957) , 
6, 0.333163, 1, 0, 0.492794,-0.00323421) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.417966,0.0403867) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.567026,-0.0043685) , 
1, 1.50214, 1, 0, 0.521546,0.00951969) , 
7, 7.38283, 1, 0, 0.5,-3.77379e-05)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443018,-0.0121013) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.741731,0.0295689) , 
6, 2.24796, 1, 0, 0.51062,-0.00363806) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.377593,0.0705953) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.517341,-0.0159288) , 
6, 1.22177, 1, 0, 0.47723,0.00767168) , 
5, 1.60265, 1, 0, 0.5,-4.08319e-05)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.509921,-0.00569871) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.286281,0.0365585) , 
8, 2.03674, 1, 0, 0.492852,-0.00263647) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.565128,0.0396779) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455503,-0.0538815) , 
9, 44.4158, 1, 0, 0.531213,0.0112089) , 
5, 2.7068, 1, 0, 0.5,-5.65364e-05)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.5427,0.00387103) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.300763,-0.031511) , 
8, 1.62188, 1, 0, 0.498475,-0.00240221) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.532625,0.0704146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.492248,-0.0283344) , 
2, -0.980198, 1, 0, 0.511121,0.0171625) , 
9, 67.9047, 1, 0, 0.5,-4.24554e-05)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.576011,0.0106539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.529966,-0.0366806) , 
9, 63.4961, 1, 0, 0.570278,0.00476397) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.408212,-0.0148245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483216,0.052506) , 
9, 68.9074, 1, 0, 0.418035,-0.00565966) , 
5, 0.419627, 1, 0, 0.5,-4.77533e-05)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.474335,-0.00127844) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.623338,0.0311176) , 
5, 3.54528, 1, 0, 0.487931,0.00151112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.633874,-0.0197784) , 
6, 3.17019, 1, 0, 0.5,-3.53167e-05)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.502953,-0.00229882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.4352,0.0229893) , 
5, 1.88297, 1, 0, 0.491811,0.00189052) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.555023,-0.0342863) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.53949,0.0210883) , 
7, 5.81692, 1, 0, 0.549046,-0.0114279) , 
5, 3.10114, 1, 0, 0.5,-1.50976e-05)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491524,0.0156905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.648654,-0.00776166) , 
4, 1.97101, 1, 0, 0.570278,0.00464917) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.308815,-0.0240856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507891,0.00838196) , 
4, 2.00807, 1, 0, 0.418035,-0.00544003) , 
5, 0.419627, 1, 0, 0.5,-8.17282e-06)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.557337,0.0215154) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.460849,-0.014104) , 
7, 3.02108, 1, 0, 0.488366,-0.00390087) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.562397,-0.0123652) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.483524,0.018336) , 
7, 3.96557, 1, 0, 0.516387,0.00545653) , 
3, 1.0297, 1, 0, 0.5,-1.57697e-05)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.496435,-0.000943108) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.570391,0.018122) , 
5, 2.73418, 1, 0, 0.509116,0.00216749) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.403388,0.0274235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.475297,-0.0392577) , 
4, 2.44002, 1, 0, 0.447176,-0.0126269) , 
3, 2.05941, 1, 0, 0.5,-9.93962e-06)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503049,-0.000711759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.45819,0.0461262) , 
5, 1.88595, 1, 0, 0.49994,0.00252535) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.534511,0.0156976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.42458,-0.0671432) , 
9, 44.4099, 1, 0, 0.500201,-0.0084702) , 
5, 2.31246, 1, 0, 0.5,-7.24609e-06)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.599837,-0.0409246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.489985,0.0010737) , 
8, 0.315807, 1, 0, 0.497805,-0.00160969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524709,0.019858) , 
9, 76.7218, 1, 0, 0.5,-1.45744e-05)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660748,0.0304198) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.517853,0.000321087) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.16569,-0.0362847) , 
0, 5.0198, 1, 0, 0.489795,-0.00172019) , 
8, 0.260583, 1, 0, 0.5,-2.36546e-06)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.603671,-0.0191768) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.702331,0.0388002) , 
2, -0.980198, 1, 0, 0.661121,0.012544) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498952,0.00332343) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.385447,-0.0249276) , 
9, 52.8329, 1, 0, 0.477431,-0.00177078) , 
8, 0.359258, 1, 0, 0.5,-1.20248e-05)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.578791,-0.0492891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510137,0.00771171) , 
8, 0.721492, 1, 0, 0.530202,-0.00730559) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.647205,0.0200351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361814,-0.00644097) , 
8, 0.721069, 1, 0, 0.483066,0.00409149) , 
9, 28.2276, 1, 0, 0.5,-2.96756e-06)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551251,0.0378877) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.551114,-0.00766981) , 
7, 2.18603, 1, 0, 0.551129,-0.00253486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396324,0.0448793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.295654,-0.0241794) , 
2, -0.980198, 1, 0, 0.341739,0.00792423) , 
8, 1.47758, 1, 0, 0.5,1.90335e-05)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406551,-0.00942492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660458,0.0140786) , 
6, 0.864599, 1, 0, 0.564191,0.00413817) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412022,-0.0128317) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.487831,0.0428583) , 
9, 68.9074, 1, 0, 0.422073,-0.00505056) , 
5, 0.498495, 1, 0, 0.5,-1.21539e-05)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374913,-0.00411675) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.535543,0.052045) , 
1, 2.0385, 1, 0, 0.400696,0.00482358) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.563216,-0.0317481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.625928,0.0119846) , 
2, -0.980198, 1, 0, 0.601252,-0.00493627) , 
1, 2.31337, 1, 0, 0.5,-8.93621e-06)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.379094,-0.0168321) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.383766,0.0413094) , 
7, 5.43536, 1, 0, 0.381269,0.009761) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.280611,-0.0512316) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.550806,0.000864905) , 
1, 1.42879, 1, 0, 0.531217,-0.00256095) , 
1, 1.15688, 1, 0, 0.5,4.29072e-06)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423969,0.0284251) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.319373,-0.0270928) , 
7, 6.36003, 1, 0, 0.390426,0.0104479) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336417,-0.0298098) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.545159,0.00103788) , 
3, 0.0792079, 1, 0, 0.523036,-0.00222863) , 
4, 0.717113, 1, 0, 0.5,-2.65661e-05)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373996,-0.00579063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384108,0.0735812) , 
5, 1.55984, 1, 0, 0.375849,0.00784324) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.30763,-0.0491713) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.586266,0.00103534) , 
6, 0.692053, 1, 0, 0.558174,-0.00371999) , 
1, 1.60942, 1, 0, 0.5,-3.05514e-05)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.572416,0.00968041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512251,-0.0269509) , 
3, 2.05941, 1, 0, 0.564191,0.00446004) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.311376,-0.0214719) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.510261,0.00562023) , 
4, 2.00807, 1, 0, 0.422073,-0.00555239) , 
5, 0.498495, 1, 0, 0.5,-6.23229e-05)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.360928,-0.00264027) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.379695,0.0617133) , 
5, 1.88643, 1, 0, 0.363697,0.00636898) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.416676,-0.0439579) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.601696,0.000416264) , 
1, 1.65996, 1, 0, 0.583171,-0.00395613) , 
6, 0.979879, 1, 0, 0.5,-4.33705e-05)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.549482,-0.000720581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.352885,0.0329881) , 
8, 1.74885, 1, 0, 0.519087,0.00414601) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.511914,0.00130522) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.209219,-0.0675396) , 
8, 1.64971, 1, 0, 0.463588,-0.00805156) , 
5, 1.36604, 1, 0, 0.5,-4.89231e-05)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.492319,0.000354278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400424,-0.0314758) , 
5, 2.96186, 1, 0, 0.486492,-0.00158221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.620144,0.0148404) , 
5, 3.65322, 1, 0, 0.5,-7.07096e-05)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.372108,-0.00494742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.627166,0.0691064) , 
6, 1.64565, 1, 0, 0.406857,0.00511321) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.642678,0.00799626) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.363421,-0.0287443) , 
8, 1.25678, 1, 0, 0.558324,-0.00327206) , 
4, 1.57744, 1, 0, 0.5,-4.32379e-05)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373316,-0.00428326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.49371,0.042588) , 
4, 2.30163, 1, 0, 0.398729,0.00536696) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.559644,-0.0256573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.66893,0.0136962) , 
1, 3.0237, 1, 0, 0.614024,-0.00609131) , 
6, 1.49864, 1, 0, 0.5,-2.2825e-05)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.373996,-0.00113933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384108,0.049491) , 
5, 1.55984, 1, 0, 0.375849,0.00764946) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.658424,0.02637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.544209,-0.00833732) , 
9, 19.416, 1, 0, 0.558174,-0.00359524) , 
1, 1.60942, 1, 0, 0.5,-7.43063e-06)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.543058,0.000219812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331644,0.0394262) , 
5, 0.780169, 1, 0, 0.519087,0.00402367) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.410052,0.00594625) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.548582,-0.0314833) , 
6, 2.16569, 1, 0, 0.463588,-0.00770958) , 
5, 1.36604, 1, 0, 0.5,-1.15785e-05)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.500514,0.000383955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.386713,-0.0432125) , 
5, 2.22936, 1, 0, 0.492852,-0.00246952) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.487411,0.0375995) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.571318,-0.0130027) , 
6, 2.16658, 1, 0, 0.531213,0.0107064) , 
5, 2.7068, 1, 0, 0.5,-1.43346e-05)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.435209,0.000149974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.577019,-0.0483342) , 
1, 3.18986, 1, 0, 0.446587,-0.00322319) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669107,0.0435922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.673365,-0.00422478) , 
4, 2.95369, 1, 0, 0.671976,0.0103147) , 
6, 2.42088, 1, 0, 0.5,-1.4958e-05)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.316563,-0.0307004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.497435,0.000213287) , 
4, 0.26422, 1, 0, 0.487371,-0.00139582) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.678567,0.0232171) , 
4, 4.44521, 1, 0, 0.5,9.61949e-06)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669755,0.00800908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.582808,-0.0472122) , 
7, 6.37, 1, 0, 0.643191,-0.00812743) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471239,0.00543077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.215875,-0.0410961) , 
8, 2.14815, 1, 0, 0.454217,0.00260455) , 
8, 0.523718, 1, 0, 0.5,4.49763e-06)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.498084,0.000975695) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.470131,-0.0228804) , 
9, 56.3923, 1, 0, 0.492794,-0.00299137) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.542319,-0.0121687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.50398,0.0281338) , 
9, 32.6568, 1, 0, 0.521546,0.00895634) , 
7, 7.38283, 1, 0, 0.5,3.04524e-06)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.76851,0.0149314) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.455543,-0.00931393) , 
0, 2.05941, 1, 0, 0.551129,-0.00274875) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.368527,0.0242203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.258351,-0.0405193) , 
5, 1.91812, 1, 0, 0.341739,0.00850911) , 
8, 1.47758, 1, 0, 0.5,1.87998e-07)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.396158,0.0222505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.507884,-0.0108164) , 
6, 0.205708, 1, 0, 0.488366,-0.00447866) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.367691,-0.0129831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.60672,0.0191608) , 
6, 1.67178, 1, 0, 0.516387,0.00627635) , 
3, 1.0297, 1, 0, 0.5,-1.32889e-05)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.48412,-0.0220123) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.494113,0.00149645) , 
7, 2.55723, 1, 0, 0.492489,-0.00211737) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.459201,0.0431891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.569694,-0.00489771) , 
6, 1.778, 1, 0, 0.534594,0.00970554) , 
5, 2.78567, 1, 0, 0.5,-8.339e-06)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.605439,-0.0049627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.371426,0.0230353) , 
8, 1.38776, 1, 0, 0.535765,0.00329268) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.522228,0.00645077) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340629,-0.0234017) , 
8, 1.16521, 1, 0, 0.457205,-0.00395962) , 
7, 5.15563, 1, 0, 0.5,-8.98479e-06)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.312324,-0.0387703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.509935,0.000900826) , 
6, 0.166582, 1, 0, 0.492794,-0.00234449) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462892,-0.0031545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.680753,0.0392713) , 
4, 3.1552, 1, 0, 0.521546,0.00693834) , 
7, 7.38283, 1, 0, 0.5,-1.79608e-05)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.499359,0.0329951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.268731,-0.0208154) , 
5, 0.14688, 1, 0, 0.390426,0.00966182) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.545894,3.8311e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231238,-0.0357453) , 
8, 2.00385, 1, 0, 0.523036,-0.00204349) , 
4, 0.717113, 1, 0, 0.5,-1.0134e-05)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.54314,0.00118081) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.322282,-0.0360882) , 
8, 1.63483, 1, 0, 0.526321,-0.00162214) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.256925,-0.0203348) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.332504,0.0492894) , 
7, 4.90617, 1, 0, 0.294597,0.012479) , 
8, 1.87228, 1, 0, 0.5,-2.04159e-05)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.453273,0.0144485) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642873,-0.0100025) , 
1, 2.56497, 1, 0, 0.535765,0.00417822) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.381724,0.0129095) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.508664,-0.0183742) , 
4, 1.57744, 1, 0, 0.457205,-0.00507822) , 
7, 5.15563, 1, 0, 0.5,-3.58502e-05)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.391522,0.00332438) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.340526,-0.0626747) , 
4, 0.692197, 1, 0, 0.379335,-0.0119726) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.519226,-0.000661604) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.598022,0.0217891) , 
7, 8.03658, 1, 0, 0.534186,0.00336311) , 
4, 0.932195, 1, 0, 0.5,-2.24874e-05)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.53971,-0.00366519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.342654,0.0194874) , 
8, 1.47758, 1, 0, 0.491327,0.00177568) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423677,-0.0328272) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.694692,0.0139797) , 
6, 1.55672, 1, 0, 0.554902,-0.0113972) , 
7, 8.40363, 1, 0, 0.5,-2.13215e-05)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.553091,-0.0191634) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.642752,0.0218368) , 
2, -0.980198, 1, 0, 0.606389,0.00439784) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.428257,0.0184152) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.367985,-0.0241976) , 
2, -0.980198, 1, 0, 0.394776,-0.00438993) , 
8, 0.91842, 1, 0, 0.5,-2.02324e-05)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.451817,0.000678146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.64375,-0.0295517) , 
6, 2.70511, 1, 0, 0.470109,-0.00175437) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.60863,-0.016403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.708644,0.0311895) , 
2, -0.980198, 1, 0, 0.670185,0.00989676) , 
1, 3.31901, 1, 0, 0.5,-1.37217e-05)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45377,-0.0288882) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.271235,0.0218467) , 
0, 3.0495, 1, 0, 0.374881,-0.00944883) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.412079,0.0297009) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.531652,-0.000722945) , 
1, 0.704677, 1, 0, 0.522452,0.00170174) , 
4, 0.645418, 1, 0, 0.5,5.27096e-06)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.382321,0.0107517) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.343509,-0.0444333) , 
6, 0.424844, 1, 0, 0.367273,-0.0103654) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.486165,-0.0181668) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.532224,0.00500293) , 
7, 2.27883, 1, 0, 0.526924,0.00209595) , 
3, 0.0792079, 1, 0, 0.5,-5.54782e-06)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.617022,0.0137531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.272899,-0.030312) , 
8, 1.63495, 1, 0, 0.563096,0.00624923) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.470489,-0.000710368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.441575,-0.0340474) , 
9, 72.3132, 1, 0, 0.467955,-0.0031915) , 
7, 3.29963, 1, 0, 0.5,-1.17476e-05)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.491423,0.000379708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408651,-0.0273323) , 
5, 3.0954, 1, 0, 0.486398,-0.00121703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.638579,0.0139686) , 
5, 3.81096, 1, 0, 0.5,-1.0898e-05)    );
   return;
};
 
// Clean up
inline void Readall::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double Readall::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
